### ISSUE TITLE
No module named 'requests'

### ISSUE THREAD

**Issue by KnightKilito** [RShock/zhenxun_plugin_onimai#9]
rt

```bash
03-15 01:18:36 [ERROR] nonebot | Failed to import "zhenxun_plugin_onimai"
Traceback (most recent call last):
  File "/home/zhenxun_bot/bot.py", line 15, in <module>
    nonebot.load_plugins("extensive_plugin")
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-UH4sDRIh-py3.9/lib/python3.9/site-packages/nonebot/plugin/load.py", line 45, in load_plugins
    return manager.load_all_plugins()
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-UH4sDRIh-py3.9/lib/python3.9/site-packages/nonebot/plugin/manager.py", line 168, in load_all_plugins
    return set(
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-UH4sDRIh-py3.9/lib/python3.9/site-packages/nonebot/plugin/manager.py", line 169, in <genexpr>
    filter(None, (self.load_plugin(name) for name in self.available_plugins))
> File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-UH4sDRIh-py3.9/lib/python3.9/site-packages/nonebot/plugin/manager.py", line 145, in load_plugin
    module = importlib.import_module(
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "/root/.cache/pypoetry/virtualenvs/zhenxun-bot-UH4sDRIh-py3.9/lib/python3.9/site-packages/nonebot/plugin/manager.py", line 233, in exec_module
    super().exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/zhenxun_bot/extensive_plugin/zhenxun_plugin_onimai/__init__.py", line 3, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'
```

**Comment by KnightKilito** [comment]
重启几次就好了……

**Comment by RShock** [comment]
按理说，需要运行
pip install requests
插件依赖全部需要手动加是真寻的特色（大概

**Comment by Cxyofficial** [comment]
一样的问题 请问怎么解决@RShock
